---
- name: Client side samba
  hosts: all
  tasks:
        - name: Install packages
          yum:
                name: samba-client, cifs-utils
                state: latest
       # - name: Check for server shares
        #  command: smbclient -L 192.168.122.67
        - name: Add Samba Users to System
          user:
                name: '{{ item.n }}'
                uid: '{{ item.uid }}'
          with_items:
                - { n: tom, uid: 2001}
                - { n: jerry, uid: 2002}
        - name: Create credential file
          lineinfile:
                path: /etc/abc.txt
               # regexp: '{{ item.regex }}'
                line: '{{ item }}'
                create: yes
          with_items:
                - username=tom
                - password=password
        - name: Create mount point
          file:
                path: /mnt/smbshare
                state: directory
        - name: mount the shares
          mount:
                path: /mnt/smbshare
                backup: yes
                src: //192.168.122.205/sharename
                fstype: cifs
                opts: defaults,_netdev,multiuser,sec=ntlmssp,credentials=/etc/abc.txt
                state: present
