---
- name: Share a directory through Samba
  hosts: all
  tasks:
        - name: Install samba package
          yum:
                name: samba, samba-client, cifs-utils
                state: latest
        - name: Create the directory to be shared
          file:
                path: /samba
                state: directory
                mode: "2775" 
        - name: Make changes in configuration file
          blockinfile:
                path: /etc/samba/smb.conf  
                backup: yes
                block: |
                        [sharename]
                        path = /samba
                        browseable = yes
                        valid users = tom, jerry
                        write list = tom
                        read list = jerry
        - name: Add the user
          user:
                name: '{{ item.n }}'
                shell: /sbin/nologin
                uid: '{{ item.uid }}'
          with_items:
                - { n: tom, uid: 2001 }
                - { n: jerry, uid: 2002 }
          become: true
        - name: Add samba password
          shell: echo -ne "password\npassword\n" | smbpasswd -a -s '{{ item }}'
          with_items:
                - tom
                - jerry
        - name: Add selinux context to file
          sefcontext:
                target: '/samba(/.*)?'
                setype: samba_share_t
                state: present
                reload: true
        - name: Reload the SELinux changes
          command: restorecon -RFv /samba
        - name: Start the service
          service:
                name:  '{{ item }}'
                state: started
                enabled: yes
          with_items:
                - smb
                - nmb
       # - name: Start the smb  service
        #  service:
         #       name:  smb
          #      state: started
           #     enabled: yes
        - name: Add firewall
          firewalld:
                service: samba
                permanent: yes
                immediate: true
                state: enabled
