---
- name: Client side samba
  hosts: all
  tasks:
        - name: Install packages
          yum:
                name: samba-client, cifs-utils
                state: latest
       # - name: Check for server shares
        #  command: smbclient -L 192.168.122.67
        - name: Add Samba Users to System
          user:
                name: tom
                uid: 2001
        - name: Add smb password to user
          command: echo -ne "password\npassword\n" | smbpasswd -a -s tom
        - name: Create mount point
          file:
                path: /mnt/smbshare
                state: directory
        - name: mount the shares
          mount:
                path: /mnt/smbshare
                backup: yes
                src: //192.168.122.67/sharename
                fstype: cifs
                opts: default,_netdev
                state: present
