---
- name: "HTTPD task"
  hosts: all
  tasks:
  - name: "Install httpd package"
    yum:
      name: httpd
      state: present

  - name: "Start the service"
    service:
      name: httpd
      state: started
