---
- name: "HTTPD Task"
  hosts: all
  tasks:
        - name: "install the package"
          yum:
                name: httpd
                state: latest
        - name: "start the service"
          service:
                name: httpd
                state: started
                enabled: yes
        - name: Download the file
          get_url: 
                url: ftp://192.168.122.205/pub/file
                dest: /var/www/html/index.html
                force: yes  #if the file already exists, will override if content changes

        #- name: "Create a file"
         # lineinfile:
          #      path: /var/www/html/index.html
           #     line: This is Web Page
            #    create: yes
        - name: "Enable firewall"
          firewalld:
                service: http
                permanent: yes
                immediate: yes
                state: enabled
